// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagerCore.Data;

#nullable disable

namespace StudentManagerCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260621025840_UpdateRoleColumnToVarchar100")]
    partial class UpdateRoleColumnToVarchar100
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("StudentManagerCore.Models.AcademicYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateTime");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsCurrent");

                    b.Property<string>("YearName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("YearName");

                    b.HasKey("Id");

                    b.ToTable("AcademicYear", (string)null);
                });

            modelBuilder.Entity("StudentManagerCore.Models.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AdminID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AdminID"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("CertAuthority")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("CertNumber")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CertSubject")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("ClassID")
                        .HasColumnType("int")
                        .HasColumnName("ClassID");

                    b.Property<string>("ClassName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ClassName");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DingTalkUnionId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("DingTalkUnionId");

                    b.Property<string>("EndStage")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("EndStage");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Grade")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Grade");

                    b.Property<string>("HighestEducation")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nation")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Password");

                    b.Property<string>("Permissions")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Phone");

                    b.Property<string>("Position")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Position");

                    b.Property<string>("RealName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("RealName");

                    b.Property<string>("RegisteredDomicile")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Role")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Role");

                    b.Property<string>("SchoolType")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("SchoolType");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Username");

                    b.HasKey("AdminID");

                    b.HasIndex("DingTalkUnionId")
                        .IsUnique();

                    b.ToTable("Admin", (string)null);
                });

            modelBuilder.Entity("StudentManagerCore.Models.AiAnalysisResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnalysisResult")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("AnalysisResult");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("ExamScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("ExamScheduleId");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("ExamScheduleId", "StudentId")
                        .IsUnique();

                    b.ToTable("AiAnalysisResult", (string)null);
                });

            modelBuilder.Entity("StudentManagerCore.Models.AiClassAnalysisResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnalysisResult")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("AnalysisResult");

                    b.Property<int>("ClassInfoId")
                        .HasColumnType("int")
                        .HasColumnName("ClassInfoId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("ExamScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("ExamScheduleId");

                    b.Property<int>("GradeLevelId")
                        .HasColumnType("int")
                        .HasColumnName("GradeLevelId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("ExamScheduleId", "ClassInfoId")
                        .IsUnique();

                    b.ToTable("AiClassAnalysisResult", (string)null);
                });

            modelBuilder.Entity("StudentManagerCore.Models.AiSubjectAnalysisResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnalysisResult")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("AnalysisResult");

                    b.Property<int>("ClassInfoId")
                        .HasColumnType("int")
                        .HasColumnName("ClassInfoId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("ExamScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("ExamScheduleId");

                    b.Property<int>("GradeLevelId")
                        .HasColumnType("int")
                        .HasColumnName("GradeLevelId");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("SubjectId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("ExamScheduleId", "ClassInfoId", "SubjectId")
                        .IsUnique();

                    b.ToTable("AiSubjectAnalysisResult", (string)null);
                });

            modelBuilder.Entity("StudentManagerCore.Models.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Content");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateTime");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("TargetRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TargetRole");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.ToTable("Announcement", (string)null);
                });

            modelBuilder.Entity("StudentManagerCore.Models.AnnouncementRead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnnouncementId")
                        .HasColumnType("int")
                        .HasColumnName("AnnouncementId");

                    b.Property<DateTime>("ReadTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ReadTime");

                    b.Property<string>("TeacherPhone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TeacherPhone");

                    b.HasKey("Id");

                    b.ToTable("AnnouncementRead", (string)null);
                });

            modelBuilder.Entity("StudentManagerCore.Models.ClassInfo", b =>
                {
                    b.Property<int>("ClassInfoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ClassInfoID"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ClassName");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateTime");

                    b.Property<int>("GradeLevelID")
                        .HasColumnType("int")
                        .HasColumnName("GradeLevelID");

                    b.HasKey("ClassInfoID");

                    b.HasIndex("GradeLevelID");

                    b.ToTable("ClassInfo", (string)null);
                });

            modelBuilder.Entity("StudentManagerCore.Models.ClassSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("ClassId");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateTime");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int")
                        .HasColumnName("DayOfWeek");

                    b.Property<int>("Period")
                        .HasColumnType("int")
                        .HasColumnName("Period");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int")
                        .HasColumnName("SemesterId");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("SubjectId");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("TeacherId");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdateTime");

                    b.HasKey("Id");

                    b.HasIndex("SemesterId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("ClassId", "SemesterId", "DayOfWeek", "Period")
                        .IsUnique();

                    b.HasIndex("TeacherId", "SemesterId", "DayOfWeek", "Period");

                    b.ToTable("ClassSchedule", (string)null);
                });

            modelBuilder.Entity("StudentManagerCore.Models.ExamRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArrangeMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ArrangeMode");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateTime");

                    b.Property<int>("ExamScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("ExamScheduleId");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Grade");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("RoomName");

                    b.Property<int>("SeatCount")
                        .HasColumnType("int")
                        .HasColumnName("SeatCount");

                    b.HasKey("Id");

                    b.HasIndex("ExamScheduleId");

                    b.ToTable("ExamRoom", (string)null);
                });

            modelBuilder.Entity("StudentManagerCore.Models.ExamRoomStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExamRoomId")
                        .HasColumnType("int")
                        .HasColumnName("ExamRoomId");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int")
                        .HasColumnName("SeatNumber");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentId");

                    b.HasKey("Id");

                    b.HasIndex("ExamRoomId");

                    b.HasIndex("StudentId");

                    b.ToTable("ExamRoomStudent", (string)null);
                });

            modelBuilder.Entity("StudentManagerCore.Models.ExamSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateTime");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("EndDate");

                    b.Property<DateTime>("ExamDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ExamDate");

                    b.Property<string>("ExamType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("ExamType");

                    b.Property<string>("Grades")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Grades");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Name");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int")
                        .HasColumnName("SemesterId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("SemesterId");

                    b.ToTable("ExamSchedule", (string)null);
                });

            modelBuilder.Entity("StudentManagerCore.Models.ExamSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExamScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("ExamScheduleId");

                    b.Property<int?>("FullScore")
                        .HasColumnType("int")
                        .HasColumnName("FullScore");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("SubjectId");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("ExamScheduleId", "SubjectId")
                        .IsUnique();

                    b.ToTable("ExamSubject", (string)null);
                });

            modelBuilder.Entity("StudentManagerCore.Models.ExamSubjectTeacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("AdminId");

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("ClassId");

                    b.Property<int>("ExamScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("ExamScheduleId");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("SubjectId");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("ClassId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("ExamScheduleId", "SubjectId", "AdminId", "ClassId")
                        .IsUnique();

                    b.ToTable("ExamSubjectTeacher", (string)null);
                });

            modelBuilder.Entity("StudentManagerCore.Models.GradeLevel", b =>
                {
                    b.Property<int>("GradeLevelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GradeLevelID"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateTime");

                    b.Property<int>("EntryYear")
                        .HasColumnType("int")
                        .HasColumnName("EntryYear");

                    b.Property<string>("SchoolType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("SchoolType");

                    b.HasKey("GradeLevelID");

                    b.ToTable("GradeLevel", (string)null);
                });

            modelBuilder.Entity("StudentManagerCore.Models.GradeSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateTime");

                    b.Property<int?>("FullScore")
                        .HasColumnType("int")
                        .HasColumnName("FullScore");

                    b.Property<int>("GradeLevelId")
                        .HasColumnType("int")
                        .HasColumnName("GradeLevelId");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("SubjectId");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("GradeLevelId", "SubjectId")
                        .IsUnique();

                    b.ToTable("GradeSubject", (string)null);
                });

            modelBuilder.Entity("StudentManagerCore.Models.OperationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("ActionType");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateTime");

                    b.Property<string>("Detail")
                        .HasColumnType("longtext")
                        .HasColumnName("Detail");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("IpAddress");

                    b.Property<string>("OperatorName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("OperatorName");

                    b.Property<string>("OperatorRole")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("OperatorRole");

                    b.Property<string>("TargetName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TargetName");

                    b.Property<string>("TargetNo")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TargetNo");

                    b.HasKey("Id");

                    b.ToTable("OperationLog", (string)null);
                });

            modelBuilder.Entity("StudentManagerCore.Models.RepairRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ContactPhone");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateTime");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("CreatorName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CreatorName");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("Description");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Location");

                    b.Property<DateTime?>("PreferredTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("PreferredTime");

                    b.Property<DateTime?>("ProcessTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ProcessTime");

                    b.Property<int?>("ProcessedBy")
                        .HasColumnType("int")
                        .HasColumnName("ProcessedBy");

                    b.Property<string>("ProcessorName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ProcessorName");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext")
                        .HasColumnName("Remark");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.ToTable("RepairRequest", (string)null);
                });

            modelBuilder.Entity("StudentManagerCore.Models.SchedulePeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("EndTime");

                    b.Property<int>("PeriodNumber")
                        .HasColumnType("int")
                        .HasColumnName("PeriodNumber");

                    b.Property<int>("SettingId")
                        .HasColumnType("int")
                        .HasColumnName("SettingId");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("StartTime");

                    b.HasKey("Id");

                    b.HasIndex("SettingId", "PeriodNumber")
                        .IsUnique();

                    b.ToTable("SchedulePeriod", (string)null);
                });

            modelBuilder.Entity("StudentManagerCore.Models.ScheduleSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BreakMinutes")
                        .HasColumnType("int")
                        .HasColumnName("BreakMinutes");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateTime");

                    b.Property<int>("DaysPerWeek")
                        .HasColumnType("int")
                        .HasColumnName("DaysPerWeek");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.Property<int>("PeriodDurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("PeriodDurationMinutes");

                    b.Property<int>("PeriodsPerDay")
                        .HasColumnType("int")
                        .HasColumnName("PeriodsPerDay");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("StartTime");

                    b.HasKey("Id");

                    b.ToTable("ScheduleSetting", (string)null);
                });

            modelBuilder.Entity("StudentManagerCore.Models.Score", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClassInfoId")
                        .HasColumnType("int")
                        .HasColumnName("ClassInfoId");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateTime");

                    b.Property<DateTime>("ExamDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ExamDate");

                    b.Property<int>("ExamScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("ExamScheduleId");

                    b.Property<string>("ExamType")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("ExamType");

                    b.Property<int?>("GradeLevelId")
                        .HasColumnType("int")
                        .HasColumnName("GradeLevelId");

                    b.Property<decimal>("ScoreValue")
                        .HasColumnType("decimal(5,1)")
                        .HasColumnName("ScoreValue");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentId");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("SubjectId");

                    b.HasKey("Id");

                    b.HasIndex("ClassInfoId");

                    b.HasIndex("ExamScheduleId");

                    b.HasIndex("GradeLevelId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("StudentId", "SubjectId", "ExamScheduleId")
                        .IsUnique();

                    b.ToTable("Score", (string)null);
                });

            modelBuilder.Entity("StudentManagerCore.Models.Semester", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("int")
                        .HasColumnName("AcademicYearId");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateTime");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsCurrent");

                    b.Property<string>("SemesterName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SemesterName");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYearId");

                    b.ToTable("Semester", (string)null);
                });

            modelBuilder.Entity("StudentManagerCore.Models.SiteConfig", b =>
                {
                    b.Property<string>("ConfigKey")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ConfigKey");

                    b.Property<string>("ConfigValue")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("ConfigValue");

                    b.HasKey("ConfigKey");

                    b.ToTable("SiteConfig", (string)null);
                });

            modelBuilder.Entity("StudentManagerCore.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StudentID"));

                    b.Property<int?>("ClassID")
                        .HasColumnType("int")
                        .HasColumnName("ClassID");

                    b.Property<string>("ClassName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ClassName");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateTime");

                    b.Property<string>("CurrentResidence")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("CurrentResidence");

                    b.Property<string>("FatherName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("FatherName");

                    b.Property<string>("FatherPhone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("FatherPhone");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Gender");

                    b.Property<string>("Grade")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Grade");

                    b.Property<string>("HouseholdAddress")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("HouseholdAddress");

                    b.Property<string>("HouseholdCity")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("HouseholdCity");

                    b.Property<string>("HouseholdType")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("HouseholdType");

                    b.Property<string>("IDCardNumber")
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)")
                        .HasColumnName("IDCardNumber");

                    b.Property<string>("IsMigrantChild")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("IsMigrantChild");

                    b.Property<string>("IsMigrantWorkerChild")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("IsMigrantWorkerChild");

                    b.Property<string>("IsNonLocalHousehold")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("IsNonLocalHousehold");

                    b.Property<string>("MotherName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MotherName");

                    b.Property<string>("MotherPhone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MotherPhone");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.Property<string>("Nation")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Nation");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Remark");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Status");

                    b.Property<string>("StudentNo")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("StudentNo");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdateTime");

                    b.HasKey("StudentID");

                    b.HasIndex("IDCardNumber")
                        .IsUnique();

                    b.HasIndex("StudentNo")
                        .IsUnique();

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("StudentManagerCore.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateTime");

                    b.Property<int>("FullScore")
                        .HasColumnType("int")
                        .HasColumnName("FullScore");

                    b.Property<string>("Grade")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Grade");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("SortOrder");

                    b.HasKey("Id");

                    b.ToTable("Subject", (string)null);
                });

            modelBuilder.Entity("StudentManagerCore.Models.SubjectClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("ClassId");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("SubjectId");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId", "ClassId")
                        .IsUnique();

                    b.ToTable("SubjectClass", (string)null);
                });

            modelBuilder.Entity("StudentManagerCore.Models.SubjectTeacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("AdminId");

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("ClassId");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("SubjectId");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("ClassId");

                    b.HasIndex("SubjectId", "AdminId", "ClassId")
                        .IsUnique();

                    b.ToTable("SubjectTeacher", (string)null);
                });

            modelBuilder.Entity("StudentManagerCore.Models.TeacherSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("AdminId");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("SubjectId");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("AdminId", "SubjectId")
                        .IsUnique();

                    b.ToTable("TeacherSubject", (string)null);
                });

            modelBuilder.Entity("StudentManagerCore.Models.ClassInfo", b =>
                {
                    b.HasOne("StudentManagerCore.Models.GradeLevel", "GradeLevel")
                        .WithMany("Classes")
                        .HasForeignKey("GradeLevelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradeLevel");
                });

            modelBuilder.Entity("StudentManagerCore.Models.ClassSchedule", b =>
                {
                    b.HasOne("StudentManagerCore.Models.ClassInfo", "ClassInfo")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagerCore.Models.Semester", "Semester")
                        .WithMany()
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagerCore.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagerCore.Models.Admin", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassInfo");

                    b.Navigation("Semester");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("StudentManagerCore.Models.ExamRoom", b =>
                {
                    b.HasOne("StudentManagerCore.Models.ExamSchedule", "ExamSchedule")
                        .WithMany()
                        .HasForeignKey("ExamScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamSchedule");
                });

            modelBuilder.Entity("StudentManagerCore.Models.ExamRoomStudent", b =>
                {
                    b.HasOne("StudentManagerCore.Models.ExamRoom", "ExamRoom")
                        .WithMany("Students")
                        .HasForeignKey("ExamRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagerCore.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamRoom");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentManagerCore.Models.ExamSchedule", b =>
                {
                    b.HasOne("StudentManagerCore.Models.Semester", "Semester")
                        .WithMany()
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("StudentManagerCore.Models.ExamSubject", b =>
                {
                    b.HasOne("StudentManagerCore.Models.ExamSchedule", "ExamSchedule")
                        .WithMany("ExamSubjects")
                        .HasForeignKey("ExamScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagerCore.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamSchedule");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudentManagerCore.Models.ExamSubjectTeacher", b =>
                {
                    b.HasOne("StudentManagerCore.Models.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagerCore.Models.ClassInfo", "ClassInfo")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagerCore.Models.ExamSchedule", "ExamSchedule")
                        .WithMany()
                        .HasForeignKey("ExamScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagerCore.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("ClassInfo");

                    b.Navigation("ExamSchedule");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudentManagerCore.Models.GradeSubject", b =>
                {
                    b.HasOne("StudentManagerCore.Models.GradeLevel", "GradeLevel")
                        .WithMany()
                        .HasForeignKey("GradeLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagerCore.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradeLevel");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudentManagerCore.Models.SchedulePeriod", b =>
                {
                    b.HasOne("StudentManagerCore.Models.ScheduleSetting", "Setting")
                        .WithMany()
                        .HasForeignKey("SettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Setting");
                });

            modelBuilder.Entity("StudentManagerCore.Models.Score", b =>
                {
                    b.HasOne("StudentManagerCore.Models.ClassInfo", "ClassInfo")
                        .WithMany()
                        .HasForeignKey("ClassInfoId");

                    b.HasOne("StudentManagerCore.Models.ExamSchedule", "ExamSchedule")
                        .WithMany()
                        .HasForeignKey("ExamScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagerCore.Models.GradeLevel", "GradeLevel")
                        .WithMany()
                        .HasForeignKey("GradeLevelId");

                    b.HasOne("StudentManagerCore.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagerCore.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassInfo");

                    b.Navigation("ExamSchedule");

                    b.Navigation("GradeLevel");

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudentManagerCore.Models.Semester", b =>
                {
                    b.HasOne("StudentManagerCore.Models.AcademicYear", "AcademicYear")
                        .WithMany()
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicYear");
                });

            modelBuilder.Entity("StudentManagerCore.Models.SubjectClass", b =>
                {
                    b.HasOne("StudentManagerCore.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudentManagerCore.Models.SubjectTeacher", b =>
                {
                    b.HasOne("StudentManagerCore.Models.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagerCore.Models.ClassInfo", "ClassInfo")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagerCore.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("ClassInfo");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudentManagerCore.Models.TeacherSubject", b =>
                {
                    b.HasOne("StudentManagerCore.Models.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagerCore.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudentManagerCore.Models.ExamRoom", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("StudentManagerCore.Models.ExamSchedule", b =>
                {
                    b.Navigation("ExamSubjects");
                });

            modelBuilder.Entity("StudentManagerCore.Models.GradeLevel", b =>
                {
                    b.Navigation("Classes");
                });
#pragma warning restore 612, 618
        }
    }
}
